### ISSUE TITLE
师傅，阿里云返回上一级老卡住，麻烦看看呢

### ISSUE THREAD

**Issue by 7years-nmine** [dark-kingA/cloudTools#10]

**Comment by dark-kingA** [comment]
详细说明 什么功能点 可以吗

**Comment by 7years-nmine** [comment]
不好意思，问题解决了，昨天可能连接网络问题加载慢卡住了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月7日(星期二) 晚上8:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dark-kingA/cloudTools] 师傅，阿里云返回上一级老卡住，麻烦看看呢 (Issue #10)





 
详细说明 什么功能点 可以吗

**Comment by dark-kingA** [comment]
ok
