### ISSUE TITLE
不能下载文件

### ISSUE THREAD

**Issue by gringoddjw** [dark-kingA/cloudTools#14]
![image](https://github.com/dark-kingA/cloudTools/assets/70787258/b44c51fc-84f9-4282-9c26-c8202db93252)
会有这样的提示

**Comment by dark-kingA** [comment]
1.复制地址 去浏览器访问 如果下载不了 那说明是附件问题
2.去对应oss浏览器尝试 
多半都是附件问题 这是无法解决的
