### ISSUE TITLE
工具无法退出

### ISSUE THREAD

**Issue by ki10Moc** [dark-kingA/cloudTools#20]
系统：Sonoma14.4.1
工具版本：2024-03-14-mac-arm64
具体问题描述：在dork栏右键该工具退出无反应，需要command+q强制退出

**Comment by dark-kingA** [comment]
是的，目前有二种退出方案。
2、mac系统无法正常关闭：
2.1、电脑最左上角点击软件关闭。
2.2、command + q 关闭软件
