### ISSUE TITLE
退出失败

### ISSUE THREAD

**Issue by yuanyang-ai** [dark-kingA/cloudTools#6]
mac下无法退出，只能杀死相关进程才能退出。
<img width="697" alt="图片" src="https://github.com/dark-kingA/cloudTools/assets/63990300/8dc7a31c-9cd1-420b-a5bb-c4cddb7fd6aa">

**Comment by h3h3qaq** [comment]
Command + Q 试试

**Comment by dark-kingA** [comment]
<img width="762" alt="image" src="https://github.com/dark-kingA/cloudTools/assets/102812179/713e7d46-a96a-43d8-beab-2e879c81edee">
或者可以这么
